name: Create IAM User and Policy

on: 
  push:
    branches:
      - master  

jobs:
  create-iam-user-and-policy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create IAM User
      run: |
        aws iam create-user --user-name My-user

    - name: Create IAM Policy
      run: |
        cat <<EoF > access-policy.json
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "s3:ListBucket",
                "s3:GetObject",
                "s3:PutObject"
              ],
              "Resource": "*"
            }
          ]
        }
        EoF

        aws iam create-policy --policy-name My-Policy --policy-document file://access-policy.json

    - name: Attach IAM Policy to User
      run: |
        POLICY_ARN=$(aws iam list-policies --output json --query 'Users[0].Arn' --output text)
        aws iam attach-user-policy --user-name My-user --policy-arn $POLICY_ARN

    # - name: Create Access Key for IAM User
    #   run: |
    #     aws iam create-access-key --user-name My-user > access-keys.json
        
