name: Create IAM User, S3 Bucket, and Policy

on: [push]

jobs:
  create-iam-user-and-policy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create S3 Bucket
      run: |
        BUCKET_NAME=my-github-action-bucket
        if ! aws s3api head-bucket --bucket $BUCKET_NAME 2>/dev/null; then
          aws s3api create-bucket --bucket $BUCKET_NAME --region us-east-1
        fi

    - name: Delete Existing IAM User (if exists)
      run: |
        USER_NAME=My-user2
        if aws iam get-user --user-name $USER_NAME 2>/dev/null; then
          aws iam delete-user --user-name $USER_NAME
        fi

    - name: Create IAM User
      run: |
        aws iam create-user --user-name My-user2

    - name: Create IAM Policy
      run: |
        BUCKET_NAME=my-github-action-bucket
        cat <<EoF > access-policy.json
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "s3:ListBucket",
                "s3:GetObject",
                "s3:PutObject"
              ],
              "Resource": [
                "arn:aws:s3:::$BUCKET_NAME",
                "arn:aws:s3:::$BUCKET_NAME/*"
              ]
            }
          ]
        }
        EoF

        aws iam create-policy --policy-name MyGitHubActionUserPolicy --policy-document file://access-policy.json

    - name: Attach IAM Policy to User
      run: |
        POLICY_ARN=$(aws iam list-policies --query "Policies[?PolicyName=='MyGitHubActionUserPolicy'].Arn" --output text)
        aws iam attach-user-policy --user-name My-user2 --policy-arn $POLICY_ARN

    